name: LegendQuest
version: 1.5.0
description: |
    RPG plugin for MineCraft servers using the Bukkit API
    Allows Race, Classes, Skills and effects.
author: SableDnah
website: http://dev.bukkit.org/server-mods/legendquest/

main: me.sablednah.legendquest.Main
depend: [SQLibrary]
softdepend: [ LQSkills, Vault ]

commands:
    lq:
        description: Control the  LegendQuest plugin.
        usage: Use "/<command> help" for more info
        aliases: [legendquest,lquest,legendq]
        permission: legendquest.command
        permission-message: You don't have <permission>
    race:
        description: View or set your race.
        usage: Use "/<command> help" for more info
        aliases: [lqrace,lquestrace,legendqrace,legendquestrace]
        permission: legendquest.command.race
        permission-message: You don't have <permission>
    class:
        description: View, choose, or change your class's.
        usage: Use "/<command> help" for more info
        aliases: [lqclass,lquestclass,legendqclass,legendquestclass,clas]
        permission: legendquest.command.class
        permission-message: You don't have <permission>
    stats:
        description: Get your player stats
        usage: Use "/<command> help" for more info
        aliases: [lqstats,lqueststats,legendqstats,legendqueststats]
        permission: legendquest.command.stats
        permission-message: You don't have <permission>
    karma:
        description: Get your player karma
        usage: Use "/<command> help" for more info
        aliases: [lqkarma,lquestkarma,legendqkarma,legendquestkarma]
        permission: legendquest.command.karma
        permission-message: You don't have <permission>
    skill:
        description: View, choose, or change your Skills.
        usage: Use "/<command> help" for more info
        aliases: [lqskill,lquestskill,legendqskill,legendquestskill]
        permission: legendquest.command.skills
        permission-message: You don't have <permission>
    link:
        description: Link skill to item.
        usage: Use "/<command> help" for more info
        aliases: [lqlink,lquestlink,legendqlink,legendquestlink,bind,lqbind,lquestbind,legendbind,legendquestbind]
        permission: legendquest.command.link
        permission-message: You don't have <permission>
    roll:
        description: Test an attribute
        usage: Use "/<command> help" for more info
        aliases: [lqroll,lquestroll,legendqroll,legendquestroll,test]
        permission: legendquest.command.roll
        permission-message: You don't have <permission>
    hp:
        description: Get your health
        usage: Use "/<command> help" for more info
        aliases: [lqhp,lquesthp,legendqhp,legendquesthp]
        permission: legendquest.command.hp
        permission-message: You don't have <permission>
    plurals:
        description: Plural list commands
        usage: Use "/<command> help" for more info
        aliases: [classes,races,skills,binds,links]
        permission: legendquest.command.plurals
        permission-message: You don't have <permission>
    admin:
        description: Perform admin commands
        usage: Use "/<command> help" for more info
        aliases: [dm, lqadmin,lquestadmin,legendqadmin,legendquestadmin]
        permission: legendquest.command.admin
        permission-message: You don't have <permission>
        

permissions:
    legendquest.*:
        description: Gives access to all legendquest commands/functions.
        default: op
        children:
            legendquest.command.*: true
    legendquest.command.*:
        description: Allows user to use all basic legendquest commands.
        default: op
        children:
            legendquest.command.reload: true
            legendquest.command.race: true
            legendquest.command.class: true
            legendquest.command.skill: true
            legendquest.command.stats: true
            legendquest.command.roll: true
            legendquest.command.hp: true
            legendquest.command.link: true
            legendquest.command.karma: true
            legendquest.command.plurals: true
    legendquest.command.admin:
        description: Allows user to use legendquest admin commands.
        default: op
    legendquest.command.reload:
        description: Allows user to use legendquest reload command.
        default: false
    legendquest.command.race:
        description: Allows user to use legendquest race command.
        default: true
    legendquest.command.class:
        description: Allows user to use legendquest class command.
        default: true
    legendquest.command.skill:
        description: Allows user to use legendquest skill command.
        default: true
    legendquest.command.stats:
        description: Allows user to use legendquest stats command.
        default: true
    legendquest.command.roll:
        description: Allows user to use legendquest roll command.
        default: true
    legendquest.command.hp:
        description: Allows user to use legendquest hp command.
        default: true
    legendquest.command.karma:
        description: Allows user to use legendquest karma command.
        default: true
    legendquest.command.link:
        description: Allows user to use legendquest link command.
        default: true
    legendquest.command.plurals:
        description: Allows user to use legendquest command plurals.
        default: true
        